//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureIISBlobToLocalLogs.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AzureBlobIISLog
    {
        public string URI { get; set; }
        public long Position { get; set; }
        public System.DateTimeOffset Inserted { get; set; }
        public System.DateTimeOffset Modified { get; set; }
        public string ETag { get; set; }
        public System.DateTimeOffset AssociatedDate { get; set; }
        public string Container { get; set; }
        public string Account { get; set; }
    }
}
